### ISSUE TITLE
Add option to run `cml ci`

### ISSUE THREAD

**Issue by casperdcl** [iterative/setup-cml#58]
As per https://github.com/iterative/cml.dev/pull/195/files#r799873687:

```yaml
- uses: iterative/setup-cml@v1
  with:
    # runs `cml ci`
    ci: true  # default: true? false? string options (`ci: --unshallow`)?
```
